# 01 Introduction to Vectors

There are two key operations at the heart of Linear Algebra; vector addition and multiplication.

Linear combinations are made up of vector addition and multiplication ie $cv + dw$

## Vectors and Linear Combinations

A vector is a list of numbers `[1,2,3]` 

In [1]:
import numpy as np

### Vector Addition & Subtraction

consider the vector ($v$ = [$v_1, v_2$]) and the vector ($w$ = [$w_1, w_2$]). The corresponding elements within these vectors can be added together in the following way; $v_1 + w_1$ and $v_2 + w_2$. 

Lets let $v = [1,2]$ and $w = [3,5]$

In [17]:
v = np.array([1,2])
w = np.array([3,5])

v+w

array([4, 7])

In [19]:
# vector subtraction

a = np.array([3,4])
b = np.array([2,5])

a-b

array([ 1, -1])

# Vector Multiplication

A "scalar" $c$, can be multiplied by a vector $v$ to produce $cv$

In [18]:
v = np.array([1,2])
c = 2

c*v

array([2, 4])

In [67]:
v = np.array([[-1, 0, 1],
              [.5, -.6, .3],
              [-.7, .2, .8]])

In [72]:
def funk(v):
    with np.nditer(v, op_flags=['readwrite']) as it:
        for x in it:
            x[...] = 2 * x
    return x[...]

In [73]:
funk(v)

array(6.4)